### ISSUE TITLE
Click-and-drag causes the window to move

### ISSUE THREAD

**Issue by panangam** [ahrm/sioyek#1135]
Hi. Seriously amazing app, thank you so much for your work. 

I am on KDE-Plasma, Wayland, Arch Linux (RebornOS). Just tried installing the development branch. When I click and drag in the text to highlight, it instead **moves the entire window**. I can only start highlighting the text by **double clicking**. Behavior video included below. 

[Screencast_20240719_175844.webm](https://github.com/user-attachments/assets/b8338c1b-08f9-41de-9d48-2d2d79569619)

(I double clicked in the last part to select some text)

Seems very similar to #1075, but unlike in that issue, I cannot start selecting text at all, not just when I reach the margin.

**Comment by ahrm** [comment]
Interesting, unfortunately I can't reproduce this issue on my linux machine with i3wm. I will have to fire up a VM with KDE plasma to see if I can reproduce the issue, but it might take a while since I am busy at the moment.

**Comment by panangam** [comment]
> Interesting, unfortunately I can't reproduce this issue on my linux machine with i3wm or gnome. I will have to fire up a VM with KDE plasma to see if I can reproduce the issue, but it might take a while since I am busy at the moment.

Understandable. Let me know if I can do something to diagnose the problem further (I'm not busy).  I am not familiar with your code base yet though.

**Comment by ahrm** [comment]
The main thing is to figure out if the `mouseMoveEvent` in `main_widget.cpp` is fired when moving the mouse or not. Also you can create a simple minimal Qt application and see if the issue persists there. Also you can checkout a previous commit, e.g. this: https://github.com/ahrm/sioyek/commit/35f0d63adab81028d3ca708119a9a5e420caefe2 and see if the issue exists there, if not, you can do a git bisect to find the exact commit that causes the issue (my suspicion is that the very next commit, namely https://github.com/ahrm/sioyek/commit/f7727a8e4e6af18ae631d5a2bfa4db1f1b4d3b39 might be causing the issue).

**Comment by panangam** [comment]
Ooh thanks for the pointers. I'll try these.

**Comment by panangam** [comment]
@ahrm I've been struggling with building on Arch for a while now... I think here is the core build error I'm getting on my system

```shell
pdf_viewer/document.cpp: In lambda function:
pdf_viewer/document.cpp:1101:17: error: ‘fz_page_label’ was not declared in this scope; did you mean ‘get_page_label’?
 1101 |                 fz_page_label(context_, page, label_buffer, N);
      |                 ^~~~~~~~~~~~~
      |                 get_page_label
```

I found `fz_page_label` declared in a fitz header file, so I'm not sure what's happening...

I know it's possible to build on Arch, cause someone made a PKGBUILD for it already: https://aur.archlinux.org/packages/sioyek-git. But they had to
- manually choose to use qt6 (should we update the README in the Linux build section to use qt6 as well? it's saying qt5 right now)
- use system-installed mupdf (`libmupdf`)

I'm guessing there is no CI for this project to regularly test building on a linux system? Unfortunately I can't really diagnose the problem right now since I still can't build. Will keep trying a bit more though. If you have insight into this, please let me know.

**Comment by panangam** [comment]
@ahrm Hello. You were right on the money. 35f0d63 worked fine, and the click-and-drag problem happened immediately in f7727a8 (please disregard my previous comments about system-installed `libmupdf`). Any thought or suggestion for how to fox this?

**Comment by ahrm** [comment]
So the main thing we did in that commit was to use `QMainWindow` as the parent of root widget instead of `QQuickWidget`. This was necessary to support titlebar on MacOS. You can try to create a simple minimal Qt application with `QMainWindow` as parent of the root widget and see if the issue happens there. If it does, then it is either a Qt bug or maybe there  is a window flag which can be enabled to change the behaviour, if it does not happen there, then it might be a bug with sioyek.

**Comment by ahrm** [comment]
I installed kde-plasma on my ubuntu machine but could not reproduce this issue, maybe it has something to do with your specific configuration?

**Comment by ahrm** [comment]
It is also possible that this was a qt bug that has been fixed. I tried with qt 6.7 .

**Comment by panangam** [comment]
@ahrm Thank you for testing. I have been caught up in real life so I haven't tested this in a while. Will try with Qt 6.7 when I have time 👍.

**Comment by panangam** [comment]
I'm sad to report that I still get the exact same bug with qt 6.8 :(. Does this not happen for anybody else?

**Comment by panangam** [comment]
After updating my KDE the problem is now gone... Sorry for the false alarm 😅. Closing this now.
