### ISSUE TITLE
Build failure on Windows MSVC: error C7555 due to C++20 designated initializers

### ISSUE THREAD

**Issue by dtristany** [ahrm/sioyek#1669]
When building on Windows using MSVC (eg via GitHub Actions) the build fails during the compilation of `main_widget.cpp`. The compiler throws an error regarding the use of designated initializers, which are a C++20 feature.

Currently, `pdf_viewer_build_config.pro` globally sets `CONFIG += c++17`. MSVC strictly enforces standard flags and refuses to compile C++20 syntax under a C++17 configuration.  

### Error Log

```text
D:\a\sioyek\sioyek\pdf_viewer\main_widget.cpp(11158,9): error C7555: use of designated initializers requires at least '/std:c++20' [D:\a\sioyek\sioyek\sioyek.vcxproj]
D:\a\sioyek\sioyek\pdf_viewer\main_widget.cpp(11164,9): error C7555: use of designated initializers requires at least '/std:c++20' [D:\a\sioyek\sioyek\sioyek.vcxproj]
```
To reproduce the behavior run a Windows build using MSVC and Qt 6.11.

### Proposed Fix

Update `pdf_viewer_build_config.pro` to append `/std:c++20` to `QMAKE_CXXFLAGS` inside the `win32` block. This satisfies MSVC's requirement for designated initializers without altering the standard for macOS and Linux builds.

**Comment by ahrm** [comment]
I updated the build files in https://github.com/ahrm/sioyek/commit/65ea1ab5e32556ff060c9ea138633124ae7b77d3, I don't have access to a windows machine right now to test it it worked though.

**Comment by dtristany** [comment]
I fixed it in a slightly different way that allows other distributions to stay at C++17. 
I've tested it with Github actions on latest windows and it's working https://github.com/dtristany/sioyek/actions

I've sent you the fix in a pull request, and I've also fixed a few other things in the windows version, as well as update to latest compatible mupdf, zlib and openssl for security fixes.

For openssl I've tested the windows build without the bundled ssl and crypto DLLs and there doesn't seem to be any difference. The only thing that doesn't seem to be working is checking for udpates, but that could be because I built from source. I noticed there's no qopensslbackend.dll in my tls folder, but QT 6 on windows should fall back to Schannel for networking requests. 

If the only purpose for openssl is to check for updates, might as well let QT use the native Schannel backend and remove libssl/libcrypto, which avoids having to keep up with security fixes.

**Comment by ahrm** [comment]
Thanks I will have to test this when I have access to a windows machine. I don't have an issue with forcing c++20 for the future versions of sioyek. The ssl libraris were required for a feature we had which allowed the user to automatically download the overview papers (it doesn't work anymore, because we used an API provided by the internet archive but they had to take it down due to DDoS attacks), but I plan to bring the feature back for future versions of sioyek so we probably will need those in the future.

**Comment by dtristany** [comment]
Is it worthwhile testing new versions of mupdf, or will it just break things?

**Comment by ahrm** [comment]
There should be no problem using newer version of mupdf (as long as the included headers and the linked lib match).
