### ISSUE TITLE
Compilation error in pdf_viewer/ui.h

### ISSUE THREAD

**Issue by david-cortes** [ahrm/sioyek#156]
I get this error when I try to compile in linux through the sh script:
```
pdf_viewer/ui.h: In constructor ‘BaseSelectorWidget<T, ViewType, ProxyModelType>::BaseSelectorWidget(QStandardItemModel*, QWidget*)’:
pdf_viewer/ui.h:94:38: error: ‘class QSortFilterProxyModel’ has no member named ‘setRecursiveFilteringEnabled’
   94 |                         proxy_model->setRecursiveFilteringEnabled(true);
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Not sure whic specific QT component this is, but this is with libqt5-* headers version 5.15.2 from debian testing.

**Comment by ahrm** [comment]
Are you sure about your qt version? Because `setRecursiveFilteringEnabled` was added in 5.10:
https://doc.qt.io/qt-5/qsortfilterproxymodel.html#recursiveFilteringEnabled-prop

**Comment by david-cortes** [comment]
Just realized I had conflicting QT headers from system and anaconda in my `PATH`. Works fine with the 5.15.2 headers from debian.
